name: display
'on': push
jobs:
  reverse:
    runs-on: ubuntu-latest
    steps:
    - name: Reverse string
      run: |
        echo "today is a beautiful day " |rev
        echo "yad lufituaeb a si yadot" |rev
